package primero;
// Generated 06-feb-2017 13:15:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Partidos generated by hbm2java
 */
@Entity
@Table(name = "partidos", catalog = "liga")
public class Partidos implements java.io.Serializable {

	@Override
	public String toString() {
		return "Partidos [idPartido=" + idPartido + ", equiposByElocal=" + equiposByElocal.getIdEquipo() + ", equiposByEvisitante="
				+ equiposByEvisitante.getIdEquipo() + ", resultado=" + resultado + ", fecha=" + fecha + ", arbitro=" + arbitro + "]";
	}

	private Integer idPartido;
	private Equipos equiposByElocal;
	private Equipos equiposByEvisitante;
	private String resultado;
	private Date fecha;
	private String arbitro;

	public Partidos() {
	}

	public Partidos(Equipos equiposByElocal, Equipos equiposByEvisitante) {
		this.equiposByElocal = equiposByElocal;
		this.equiposByEvisitante = equiposByEvisitante;
	}

	public Partidos(Equipos equiposByElocal, Equipos equiposByEvisitante, String resultado, Date fecha,
			String arbitro) {
		this.equiposByElocal = equiposByElocal;
		this.equiposByEvisitante = equiposByEvisitante;
		this.resultado = resultado;
		this.fecha = fecha;
		this.arbitro = arbitro;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_partido", unique = true, nullable = false)
	public Integer getIdPartido() {
		return this.idPartido;
	}

	public void setIdPartido(Integer idPartido) {
		this.idPartido = idPartido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "elocal", nullable = false)
	public Equipos getEquiposByElocal() {
		return this.equiposByElocal;
	}

	public void setEquiposByElocal(Equipos equiposByElocal) {
		this.equiposByElocal = equiposByElocal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "evisitante", nullable = false)
	public Equipos getEquiposByEvisitante() {
		return this.equiposByEvisitante;
	}

	public void setEquiposByEvisitante(Equipos equiposByEvisitante) {
		this.equiposByEvisitante = equiposByEvisitante;
	}

	@Column(name = "resultado", length = 45)
	public String getResultado() {
		return this.resultado;
	}

	public void setResultado(String resultado) {
		this.resultado = resultado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "arbitro", length = 45)
	public String getArbitro() {
		return this.arbitro;
	}

	public void setArbitro(String arbitro) {
		this.arbitro = arbitro;
	}

}
